<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CourseOfferingTableSeeder extends Seeder {
	 
	public function run()
	{
		DB::table('course_offering')->delete();
		DB::table('course_offering')->insert(array(

			['courseNum' => 'BIO 1',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 2',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 3',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 30',
			'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 70',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 101',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 102',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 120',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 121',
			'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 130a',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 130b',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 131',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 137',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 138',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 139',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 140',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 142',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 150',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 151',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 159',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 180',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 190',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 191',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 192',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 199',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BIO 200',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			// BOTANY (20)

			['courseNum' => 'BOT 1',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],
			
			['courseNum' => 'BOT 3',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 11',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 20',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 101',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 110',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],
			
			['courseNum' => 'BOT 111',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 120',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 131',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 132',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 140',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],
			
			['courseNum' => 'BOT 141',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 142',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 150',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 152',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 160',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],
			
			['courseNum' => 'BOT 161',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 191',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 192',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'BOT 195',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			// NATURAL SCIENCE (NASC) (7)

			['courseNum' => 'NASC 1 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],
			
			['courseNum' => 'NASC 2 (MST)',
			'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'NASC 3 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'NASC 4 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'NASC 5 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'NASC 8 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'NASC 9 (MST)',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			// MICROBIOLOGY (12)

			['courseNum' => 'MCB 1',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 101',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 102',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 103',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 120',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 130',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 150',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 160',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 160.1',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 180',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 181',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'MCB 198',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],



			// WILDLIFE (3)

			['courseNum' => 'WLDL 101',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'WLDL 155',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'WLDL 198',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],



			 // ZOOLOGY

			['courseNum' => 'ZOO 1',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 2',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 3',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 91',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 113',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 115',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 117',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 122',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 140',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 142',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 145',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 146',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 148',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 149',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 150',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 151',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 152',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 155',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 160',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 170',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 173',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 174',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 177',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 180',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 185',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA'],

			['courseNum' => 'ZOO 191',
			 'section' => 'AB-1L',
			 'lecture' => 'TBA',
			 'lecturer' => 'TBA',
			 'lab' => 'TBA',
			 'labinstruct' => 'TBA']
		));
	}
}